### ISSUE TITLE
Installation issue on Archlinux

### ISSUE THREAD

**Issue by Fs02** [smashedtoatoms/asdf-openresty#2]
This guide probably will be useful for Archlinux user, maybe we can put it on readme or wiki? what do you think?

---

if you are using arch based distribution, you might need to manually specify openssl version:
```
OPENRESTY_EXTRA_CONFIGURE_OPTIONS="--with-cc-opt=-I/usr/include/openssl-1.0 --with-ld-opt=-L/usr/lib/openssl-1.0" asdf install openresty 1.11.2.2
```

if the above method still doesn't works, try using [older version of openssl on their website](https://www.openssl.org/source/old/1.0.1/).
```
# Download openssl
curl -O https://www.openssl.org/source/old/1.0.1/openssl-1.0.1u.tar.gz
tar xzf openssl-1.0.1u.tar.gz
./configure --with-openssl=openssl-1.0.1u
# Use downloaded openssl to build openresty
OPENRESTY_EXTRA_CONFIGURE_OPTIONS=--with-openssl=PATH_TO_DOWNLOADED_FILE/openssl-1.0.1u asdf install openresty 1.11.2.2
```

**Comment by smashedtoatoms** [comment]
Yea man, that is great.  Do you want to add it to the readme and submit a PR?  Someone will definitely appreciate not having to figure that out.

**Comment by Fs02** [comment]
sure :)
